server:
  port: 8080

spring:
  datasource:
      url: jdbc:h2:mem:testdb  # ✅ 인메모리 H2 데이터베이스 사용
      driver-class-name: org.h2.Driver
      username: sa
      password:

  data:
    redis:
      host: localhost
      port: 6379

  h2:
    console:
      enabled: true  # ✅ H2 콘솔 활성화 (http://localhost:8080/h2-console)
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect  # ✅ H2 용 Hibernate Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop


  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ${KAKAO_CLIENT_ID}
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "${custom.site.backUrl}/{action}/oauth2/code/{registrationId}"
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


springdoc:
  default-produces-media-type: application/json;charset=UTF-8

aladin:
  ttbkey: ttbpcyscott0129001

custom:
  jwt:
    secretKey: w92mLzTnRJ6P1qfzX7KlmFdyvRk3NhGq
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:3000"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
  prod:
    cookieDomain: book.oa.gg
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
  site:
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"
    name: Book
  accessToken:
    expirationSeconds: "#{60 * 20}"
payment:
  toss:
    secret-key: "test_sk_dummy_value_for_testing"
    client-key: "test_ck_dummy_value_for_testing"
    success-url: "http://localhost:8080/payment/success"
    fail-url: "http://localhost:8080/payment/fail"