# 파일 이름에서 .default 지운 뒤 "NEED_TO_INPUT" 부분에 key를 입력해서 사용.
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ${KAKAO_CLIENT_ID}
custom:
  jwt:
    secretKey: ${JWT_SECRET_KEY}